version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin  # Corregido: Cambiado POSTGRES-USER a POSTGRES_USER
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80  # Corregido: Cambiado PGADMIN-LISTEN-PORT a PGADMIN_LISTEN_PORT
    ports:
      - "8080:80"
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
